---
- hosts: "localhost"
  connection: "local"
  vars:
    ssh_known_hosts_file: "~/.ssh/known_hosts"

  tasks:
  - name: droplets | create
    digital_ocean: state="active" command="droplet" name="{{ item }}" size_id="62" region_id="2" image_id="13089493" ssh_key_ids="625455" wait_timeout="500" unique_name="yes"
    with_items:
      - "production-db"
      - "test-db"
    register: droplets

  - name: droplets | export as facts
    set_fact: do_instances="{{ droplets.results }}"

  - name: droplets | debug
    debug: msg="{{ droplets.results }}"

  - name: droplets | register test IP
    add_host: name="{{ item.droplet.ip_address }}" groups="test"
    when: "'test' in item.droplet.name"
    with_items: droplets.results

  - name: droplets | register production IP
    add_host: name="{{ item.droplet.ip_address }}" groups="production"
    when: "'production' in item.droplet.name"
    with_items: droplets.results

  - name: droplets | register db IP
    add_host: name="{{ item.droplet.ip_address }}" groups="db"
    when: "'db' in item.droplet.name"
    with_items: droplets.results

  - name: make sure the known hosts file exists
    file: path="{{ ssh_known_hosts_file }}" state="touch"

  - name: droplets | remove from known hosts
    shell: "ssh-keygen -R {{ item.droplet.ip_address }}"
    with_items: droplets.results

  - name: droplets | add to know hosts
    shell: "ssh-keyscan -H -T 10 {{ item.droplet.ip_address }} >> {{ ssh_known_hosts_file }}"
    with_items: droplets.results

- hosts: "db"
  remote_user: "root"
  roles:
  - "security"

- hosts: "db"
  remote_user: "{{ node_management_user }}"
  sudo: "yes"
  roles:
  - "app1db"

- hosts: "production"
  #remote_user: "{{ node_management_user }}"
  remote_user: "nodemanager"
  sudo: "yes"
  roles:
  - "dump-from-prod"

- hosts: "test"
  #remote_user: "{{ node_management_user }}"
  remote_user: "nodemanager"
  sudo: "yes"
  roles:
  - "import-to-test"

- hosts: "localhost"
  connection: "local"
  tasks:
  - name:  droplets | delete
    digital_ocean: state="deleted" command="droplet" id="{{ item.droplet.id }}" ssh_key_ids="625455" wait_timeout="500"
    with_items: droplets.results
