---
node_management_user: "nodemanager"
app:
  port: 8080
  management:
    port: 8081
  logging_file: "/var/log/rolling-update-app-api"
  repo: "https://github.com/lgueye/ansible-rolling-update.git"
  local_project_path: "/tmp/ansible-rolling-update"
  local_app_path: "/tmp/ansible-rolling-update/rolling-update-app"
  node_target_link_path: "/opt/rolling-update-app-api"
  node_source_link_path: "/opt/java-apps/rolling-update-app-api"
lb:
  port: 80
  ip: "{{ hostvars[groups['lb'][0]]['ansible_eth0']['ipv4']['address'] }}"
