---

- name: application | create deploy dir if source link does not exist
  file: state="directory" dest="{{ app.node_source_link_path }}/{{ rev }}"

- name: application | copy jar
  copy: src="{{ app.local_app_path }}/api/target/rolling-update-app-api.jar" dest="{{ app.node_source_link_path }}/{{ rev }}/"

- name: application | copy app config
  copy: src="{{ app.local_app_path }}/api/target/classes/rolling-update-app-api.yml" dest="{{ app.node_source_link_path }}/{{ rev }}/"

- name: application | copy log config
  copy: src="{{ app.local_app_path }}/api/target/classes/logback.xml" dest="{{ app.node_source_link_path }}/{{ rev }}/"

- name: unix service | copy config
  copy: src="{{ app.local_app_path }}/api/target/classes/rolling-update-app-api.sh" dest="{{ app.node_source_link_path }}/{{ rev }}/" mode="u=xrw,g=xr,o=r"

