---
- name: register clone dir existence
  stat: path="{{ app.local_project_path }}"
  register: "target_app_stats"

- name: delete clonedir if needed
  command: rm -fr {{ app.local_project_path }}
  when: target_app_stats.stat.exists == true

- name: clone
  git: repo="{{ app.repo }}" dest="{{ app.local_project_path }}" version="{{ rev }}"

- name: package
  command: mvn clean package -f {{ app.local_app_path }}/pom.xml

- name: configure api
  template: src=rolling-update-app-api.yml.j2 dest="{{ app.local_app_path }}/api/target/classes/rolling-update-app-api.yml"

- name: configure log levels
  copy: src="logback.xml" dest="{{ app.local_app_path }}/api/target/classes/logback.xml"

- name: configure unix service
  template: src="rolling-update-rolling-update-app-api.sh.j2" dest="{{ app.local_app_path }}/api/target/classes/rolling-update-app-api.sh" mode="u=xrw,g=xr,o=r"

- name: configure tests
  template: src="rolling-update-app-tests.properties.j2" dest="{{ app.local_app_path }}/tests/target/test-classes/rolling-update-app-tests.properties"
